// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDV8fhdV4AybiybUKC3YJLJO3qcKKopkc',
    appId: '1:901504027950:web:0ab0aa4bef2440c8dafebf',
    messagingSenderId: '901504027950',
    projectId: 'taifaradarapp',
    authDomain: 'taifaradarapp.firebaseapp.com',
    storageBucket: 'taifaradarapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKvwqZOk1sxgDWSg3f72tZcnblPpJCQDo',
    appId: '1:901504027950:android:53c7d29542d43f75dafebf',
    messagingSenderId: '901504027950',
    projectId: 'taifaradarapp',
    storageBucket: 'taifaradarapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW5T58bXTp9JnfnfDcPltQninXXO2v2ew',
    appId: '1:901504027950:ios:0fc4e3d0476e42b8dafebf',
    messagingSenderId: '901504027950',
    projectId: 'taifaradarapp',
    storageBucket: 'taifaradarapp.firebasestorage.app',
    iosBundleId: 'com.gideon.myflutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW5T58bXTp9JnfnfDcPltQninXXO2v2ew',
    appId: '1:901504027950:ios:2ace06c8d554bebfdafebf',
    messagingSenderId: '901504027950',
    projectId: 'taifaradarapp',
    storageBucket: 'taifaradarapp.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDV8fhdV4AybiybUKC3YJLJO3qcKKopkc',
    appId: '1:901504027950:web:1954dcf3d0fb1a7ddafebf',
    messagingSenderId: '901504027950',
    projectId: 'taifaradarapp',
    authDomain: 'taifaradarapp.firebaseapp.com',
    storageBucket: 'taifaradarapp.firebasestorage.app',
  );
}
